/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelompok4.app;
import com.kelompok4.pboprojectakhir.Database;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.awt.event.*;
import com.kelompok4.design.PanelRound;
/**
 *
 * @author Ari Family
 */
public class Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Pelanggan
     */
    public Pelanggan() {
        initComponents();
        loadData();
        
        ((PanelRound) contentpanel).setOpacity(0.7f);
        ((PanelRound) contentpanel).setRoundTopLeft(40);
        ((PanelRound) contentpanel).setRoundTopRight(40);
        ((PanelRound) contentpanel).setRoundBottomLeft(40);
        ((PanelRound) contentpanel).setRoundBottomRight(40);
        
        ((PanelRound) ButtonTambah).setRoundTopLeft(40);
        ((PanelRound) ButtonTambah).setRoundTopRight(40);
        ((PanelRound) ButtonTambah).setRoundBottomLeft(40);
        ((PanelRound) ButtonTambah).setRoundBottomRight(40);
        
        ((PanelRound) ButtonHapus).setRoundTopLeft(40);
        ((PanelRound) ButtonHapus).setRoundTopRight(40);
        ((PanelRound) ButtonHapus).setRoundBottomLeft(40);
        ((PanelRound) ButtonHapus).setRoundBottomRight(40);
        
        ((PanelRound) ButtonEdit).setRoundTopLeft(40);
        ((PanelRound) ButtonEdit).setRoundTopRight(40);
        ((PanelRound) ButtonEdit).setRoundBottomLeft(40);
        ((PanelRound) ButtonEdit).setRoundBottomRight(40);
        
        ((PanelRound) tombolpelanggan).setRoundTopLeft(40);
        ((PanelRound) tombolpelanggan).setRoundTopRight(40);
        ((PanelRound) tombolpelanggan).setRoundBottomLeft(40);
        ((PanelRound) tombolpelanggan).setRoundBottomRight(40);
        
        ((PanelRound) tombolsupplier).setRoundTopLeft(40);
        ((PanelRound) tombolsupplier).setRoundTopRight(40);
        ((PanelRound) tombolsupplier).setRoundBottomLeft(40);
        ((PanelRound) tombolsupplier).setRoundBottomRight(40);
        
    }
    
    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) tabelPelanggan.getModel();
        model.setRowCount(0);

        try {
            Connection conn = Database.getConnection();
            String query = "SELECT * FROM pelanggan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_pelanggan"),
                    rs.getString("nama_pelanggan"),
                    rs.getString("kontak_pelanggan"),
                });
            }

            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        contentpanel = new com.kelompok4.design.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelanggan = new javax.swing.JTable();
        ButtonTambah = new com.kelompok4.design.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        ButtonEdit = new com.kelompok4.design.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        ButtonHapus = new com.kelompok4.design.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        tombolpelanggan = new com.kelompok4.design.PanelRound();
        labelpelanggan = new javax.swing.JLabel();
        tombolsupplier = new com.kelompok4.design.PanelRound();
        labelsupplier = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setMaximumSize(new java.awt.Dimension(1920, 1080));
        header.setMinimumSize(new java.awt.Dimension(1280, 720));
        header.setName(""); // NOI18N
        header.setPreferredSize(new java.awt.Dimension(1280, 720));
        header.setRequestFocusEnabled(false);
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Artha");
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, 79, 24));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Dasbor");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);

        jButton5.setContentAreaFilled(false);

        jButton5.setFocusPainted(false);

        jButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        header.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 6, 95, 32));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Catatan Transaksi");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);

        jButton6.setContentAreaFilled(false);

        jButton6.setFocusPainted(false);

        jButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        header.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 6, -1, 32));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Utang/Piutang");
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);

        jButton7.setContentAreaFilled(false);

        jButton7.setFocusPainted(false);

        jButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        header.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 6, -1, 32));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Stok");
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);

        jButton8.setContentAreaFilled(false);

        jButton8.setFocusPainted(false);

        jButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        header.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 6, -1, 32));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Profil");
        jButton9.setBorder(null);
        jButton9.setBorderPainted(false);

        jButton9.setContentAreaFilled(false);

        jButton9.setFocusPainted(false);

        jButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        header.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 6, -1, 32));

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 854, 50));

        contentpanel.setBackground(new java.awt.Color(255, 255, 255));
        contentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama Pelanggan", "Kontak Pelanggan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelPelanggan);

        contentpanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 670, 260));

        ButtonTambah.setBackground(new java.awt.Color(124, 195, 223));
        ButtonTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTambahMouseClicked(evt);
            }
        });
        ButtonTambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tambah");
        ButtonTambah.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, -1));

        contentpanel.add(ButtonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 200, 40));

        ButtonEdit.setBackground(new java.awt.Color(124, 195, 223));
        ButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEditMouseClicked(evt);
            }
        });
        ButtonEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Edit");
        ButtonEdit.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 210, -1));

        contentpanel.add(ButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 210, 40));

        ButtonHapus.setBackground(new java.awt.Color(124, 195, 223));
        ButtonHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonHapusMouseClicked(evt);
            }
        });
        ButtonHapus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hapus");
        ButtonHapus.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, -1));

        contentpanel.add(ButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 40));

        getContentPane().add(contentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 770, 340));

        tombolpelanggan.setBackground(new java.awt.Color(124, 195, 223));
        tombolpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolpelangganMouseClicked(evt);
            }
        });
        tombolpelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelpelanggan.setBackground(new java.awt.Color(255, 255, 255));
        labelpelanggan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelpelanggan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpelanggan.setText("Pelanggan");
        tombolpelanggan.add(labelpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 40));

        getContentPane().add(tombolpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 230, -1));

        tombolsupplier.setBackground(new java.awt.Color(124, 195, 223));
        tombolsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolsupplierMouseClicked(evt);
            }
        });
        tombolsupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelsupplier.setBackground(new java.awt.Color(124, 195, 223));
        labelsupplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelsupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelsupplier.setText("Supplier");
        tombolsupplier.add(labelsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 40));

        getContentPane().add(tombolsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 230, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        Background.setMaximumSize(new java.awt.Dimension(1920, 1080));
        Background.setName(""); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
        dashboard1 dashboardFrame = new dashboard1();
        dashboardFrame.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        CatatanTransaksi catatantransaksiFrame = new CatatanTransaksi();
        catatantransaksiFrame.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        dispose();
        UtangPiutang utangpiutangFrame = new UtangPiutang();
        utangpiutangFrame.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        dispose();
        Stok stokFrame = new Stok();
        stokFrame.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tombolpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolpelangganMouseClicked
        

    }//GEN-LAST:event_tombolpelangganMouseClicked

    private void tombolsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolsupplierMouseClicked
        Supplier SupplierWindow = new Supplier();
                SupplierWindow.setVisible(true);

    }//GEN-LAST:event_tombolsupplierMouseClicked

    private void ButtonTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTambahMouseClicked
        TambahPelanggan TambahPelangganWindow = new TambahPelanggan();
                TambahPelangganWindow.setVisible(true);

    }//GEN-LAST:event_ButtonTambahMouseClicked

    private void ButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEditMouseClicked
        int selectedRow = tabelPelanggan.getSelectedRow();
        if (selectedRow != -1) {
            String idPelanggan = tabelPelanggan.getValueAt(selectedRow, 0).toString();
            

            try {
                EditPelanggan editPelangganWindow = new EditPelanggan(idPelanggan);
                editPelangganWindow.setVisible(true);
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit.");
        }
    }//GEN-LAST:event_ButtonEditMouseClicked

    private void ButtonHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHapusMouseClicked
        int selectedRow = tabelPelanggan.getSelectedRow();
        if (selectedRow != -1) {
            String idPelanggan = tabelPelanggan.getValueAt(selectedRow, 0).toString();

            try {
                Connection conn = Database.getConnection();
                String query = "DELETE FROM pelanggan WHERE id_pelanggan = ?";
                PreparedStatement stmt = conn.prepareStatement(query);
                stmt.setString(1, idPelanggan);
                stmt.executeUpdate();

                conn.close();
                loadData();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.");
        }
    }//GEN-LAST:event_ButtonHapusMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel ButtonEdit;
    private javax.swing.JPanel ButtonHapus;
    private javax.swing.JPanel ButtonTambah;
    private javax.swing.JPanel contentpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelpelanggan;
    private javax.swing.JLabel labelsupplier;
    private javax.swing.JTable tabelPelanggan;
    private javax.swing.JPanel tombolpelanggan;
    private javax.swing.JPanel tombolsupplier;
    // End of variables declaration//GEN-END:variables
}
