/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectakhirpbo.app;

import java.awt.Color;

/**
 *
 * @author muham
 */
public class TransaksiJual extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiJual
     */
    public TransaksiJual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jHeader = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        ContentPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        ButtonInput = new javax.swing.JButton();
        ButtonBeli = new javax.swing.JButton();
        ButtonJual = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        jMenu = new javax.swing.JPanel();
        ButtonPanduan = new javax.swing.JButton();
        ButtonHome = new javax.swing.JButton();
        ButtonLaporan = new javax.swing.JButton();
        ButtonStok = new javax.swing.JButton();
        ButtonTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jHeader.setBackground(new java.awt.Color(147, 70, 51));
        jHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        Judul.setText("Transaksi");
        jHeader.add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        getContentPane().add(jHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 80));

        ContentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(147, 70, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("FORM PENJUALAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Uang Masuk       :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 170, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Kode Barang      :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Nama Barang     :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Jumlah Barang :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 170, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 350, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 350, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 350, 30));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 350, 30));

        ButtonInput.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        ButtonInput.setText("Input");
        ButtonInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInputActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 120, -1));

        ContentPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 710, 380));

        ButtonBeli.setBackground(new java.awt.Color(202, 122, 102));
        ButtonBeli.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonBeli.setText("Pembelian");
        ButtonBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBeliActionPerformed(evt);
            }
        });
        ContentPanel.add(ButtonBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        ButtonJual.setBackground(new java.awt.Color(202, 122, 102));
        ButtonJual.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonJual.setText("Penjualan");
        ButtonJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonJualActionPerformed(evt);
            }
        });
        ContentPanel.add(ButtonJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        Background.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/3274262.jpg"))); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ContentPanel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 560));

        getContentPane().add(ContentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1270, 560));

        jMenu.setBackground(new java.awt.Color(202, 122, 102));
        jMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonPanduan.setBackground(new java.awt.Color(202, 122, 102));
        ButtonPanduan.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonPanduan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/user-guide_10015187(1).png"))); // NOI18N
        ButtonPanduan.setText("Panduan");
        ButtonPanduan.setBorder(null);
        ButtonPanduan.setFocusPainted(false);
        ButtonPanduan.setMargin(new java.awt.Insets(2, 14, 2, 14));
        ButtonPanduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonPanduanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonPanduanMouseExited(evt);
            }
        });
        ButtonPanduan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPanduanActionPerformed(evt);
            }
        });
        jMenu.add(ButtonPanduan, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 150, 50));

        ButtonHome.setBackground(new java.awt.Color(202, 122, 102));
        ButtonHome.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/home_263115(4).png"))); // NOI18N
        ButtonHome.setText("Home");
        ButtonHome.setBorder(null);
        ButtonHome.setFocusPainted(false);
        ButtonHome.setMargin(new java.awt.Insets(2, 14, 2, 14));
        ButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonHomeMouseExited(evt);
            }
        });
        ButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHomeActionPerformed(evt);
            }
        });
        jMenu.add(ButtonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 50));

        ButtonLaporan.setBackground(new java.awt.Color(202, 122, 102));
        ButtonLaporan.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/chart_2489023(3.png"))); // NOI18N
        ButtonLaporan.setText("Laporan");
        ButtonLaporan.setBorder(null);
        ButtonLaporan.setFocusPainted(false);
        ButtonLaporan.setMargin(new java.awt.Insets(2, 14, 2, 14));
        ButtonLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonLaporanMouseExited(evt);
            }
        });
        ButtonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLaporanActionPerformed(evt);
            }
        });
        jMenu.add(ButtonLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, 50));

        ButtonStok.setBackground(new java.awt.Color(202, 122, 102));
        ButtonStok.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonStok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/inventory_12964148(4).png"))); // NOI18N
        ButtonStok.setText("Stok");
        ButtonStok.setBorder(null);
        ButtonStok.setFocusPainted(false);
        ButtonStok.setMargin(new java.awt.Insets(2, 14, 2, 14));
        ButtonStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonStokMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonStokMouseExited(evt);
            }
        });
        ButtonStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStokActionPerformed(evt);
            }
        });
        jMenu.add(ButtonStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 110, 50));

        ButtonTransaksi.setBackground(new java.awt.Color(202, 122, 102));
        ButtonTransaksi.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        ButtonTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/projectakhirpbo/app/img/bill_1052897(1).png"))); // NOI18N
        ButtonTransaksi.setText("Transaksi");
        ButtonTransaksi.setBorder(null);
        ButtonTransaksi.setFocusPainted(false);
        ButtonTransaksi.setMargin(new java.awt.Insets(2, 14, 2, 14));
        ButtonTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonTransaksiMouseExited(evt);
            }
        });
        ButtonTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTransaksiActionPerformed(evt);
            }
        });
        jMenu.add(ButtonTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 150, 50));

        getContentPane().add(jMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1270, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void ButtonInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInputActionPerformed

    private void ButtonBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBeliActionPerformed
        // TODO add your handling code here:
        dispose();
        Transaksi transaksiFrame = new Transaksi();
        transaksiFrame.setVisible(true);
    }//GEN-LAST:event_ButtonBeliActionPerformed

    private void ButtonJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonJualActionPerformed
        // TODO add your handling code here:
        dispose();
        TransaksiJual transaksiFrame = new TransaksiJual();
        transaksiFrame.setVisible(true);
    }//GEN-LAST:event_ButtonJualActionPerformed

    private void ButtonPanduanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPanduanMouseEntered
        // TODO add your handling code here:
        ButtonPanduan.setBackground(new Color(237, 210, 203));
    }//GEN-LAST:event_ButtonPanduanMouseEntered

    private void ButtonPanduanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonPanduanMouseExited
        // TODO add your handling code here:
        ButtonPanduan.setBackground(new Color(202, 122, 102));
    }//GEN-LAST:event_ButtonPanduanMouseExited

    private void ButtonPanduanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPanduanActionPerformed
        // TODO add your handling code here:
        dispose();
        PanduanPengguna panduanFrame = new PanduanPengguna();
        panduanFrame.setVisible(true);
    }//GEN-LAST:event_ButtonPanduanActionPerformed

    private void ButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseEntered
        // TODO add your handling code here:
        ButtonHome.setBackground(new Color(237, 210, 203));
    }//GEN-LAST:event_ButtonHomeMouseEntered

    private void ButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonHomeMouseExited
        // TODO add your handling code here:
        ButtonHome.setBackground(new Color(202, 122, 102));
    }//GEN-LAST:event_ButtonHomeMouseExited

    private void ButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHomeActionPerformed
        // TODO add your handling code here:
        dispose();
        Home homeFrame = new Home();
        homeFrame.setVisible(true);
    }//GEN-LAST:event_ButtonHomeActionPerformed

    private void ButtonLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLaporanMouseEntered
        // TODO add your handling code here:
        ButtonLaporan.setBackground(new Color(237, 210, 203));
    }//GEN-LAST:event_ButtonLaporanMouseEntered

    private void ButtonLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonLaporanMouseExited
        // TODO add your handling code here:
        ButtonLaporan.setBackground(new Color(202, 122, 102));
    }//GEN-LAST:event_ButtonLaporanMouseExited

    private void ButtonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLaporanActionPerformed
        // TODO add your handling code here:
        dispose();
        Laporan laporanFrame = new Laporan();
        laporanFrame.setVisible(true);
    }//GEN-LAST:event_ButtonLaporanActionPerformed

    private void ButtonStokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStokMouseEntered
        // TODO add your handling code here:
        ButtonStok.setBackground(new Color(237, 210, 203));
    }//GEN-LAST:event_ButtonStokMouseEntered

    private void ButtonStokMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonStokMouseExited
        // TODO add your handling code here:
        ButtonStok.setBackground(new Color(202, 122, 102));
    }//GEN-LAST:event_ButtonStokMouseExited

    private void ButtonStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStokActionPerformed
        // TODO add your handling code here:
        dispose();
        Stok stokFrame = new Stok();
        stokFrame.setVisible(true);
    }//GEN-LAST:event_ButtonStokActionPerformed

    private void ButtonTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTransaksiMouseEntered
        // TODO add your handling code here:
        ButtonTransaksi.setBackground(new Color(237, 210, 203));
    }//GEN-LAST:event_ButtonTransaksiMouseEntered

    private void ButtonTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTransaksiMouseExited
        // TODO add your handling code here:
        ButtonTransaksi.setBackground(new Color(202, 122, 102));
    }//GEN-LAST:event_ButtonTransaksiMouseExited

    private void ButtonTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTransaksiActionPerformed
        // TODO add your handling code here:
        dispose();
        Transaksi transaksiFrame = new Transaksi();
        transaksiFrame.setVisible(true);
    }//GEN-LAST:event_ButtonTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiJual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiJual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ButtonBeli;
    private javax.swing.JButton ButtonHome;
    private javax.swing.JButton ButtonInput;
    private javax.swing.JButton ButtonJual;
    private javax.swing.JButton ButtonLaporan;
    private javax.swing.JButton ButtonPanduan;
    private javax.swing.JButton ButtonStok;
    private javax.swing.JButton ButtonTransaksi;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JLabel Judul;
    private javax.swing.JPanel jHeader;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
